### ISSUE TITLE
...Invalid sparse file format at header magi. Failed to read sparse file

### ISSUE THREAD

**Issue by Orthoxodus** [SoulHunter24/android-tool#1]
I'm getting this error when I try to mount the system.img:

*** UNPACK SETTINGS ***
SPARSE_IMG = /home/yordan03/android-tool/system.img
RAW_IMG = /home/yordan03/android-tool/system.raw_img
M_DIR = /mnt/sat/loop

unpacking system.img to system.raw_img
...Invalid sparse file format at header magi
Failed to read sparse file
 Done
mounting system.raw_img to /mnt/sat/loop
...mount: /mnt/sat/loop: /home/yordan03/android-tool/system.raw_img is not a block device; try "-o loop".
 Done
*** File is empty

**Comment by Heliwrenaid** [comment]
Hi,
First of all I assume that this 'system.img' is GSI?
It seems that it is not a sparse image file (it can be already a raw image). You can try to mount it manually:
```
su
mkdir -p /mnt/sat/loop
mount system.img /mnt/sat/loop
```
If you see some files in /mnt/sat/loop, it means that mounting was successful. Then (if you needed) you can create a sparse image file using:
```
sat -r system.img
```

PS:
If it is really a raw image file you can also just convert raw image to sparse image:
```
sat -r system.img system-sparse.img
```
And then you are able to use SAT like in documentation.
